#pragma once
#define OPTION_NORMAL_WIDTH 120
#define OPTION_NORMAL_HEIGHT 20
#define OPTION_FRESH_WIDTH 50
#define OPTION_CLOSE_SIZE 15
#define WM_CREATE_NEW_PAGE WM_USER + 100 
#define WM_TITLE_CHANGE WM_USER + 101

