#pragma once
#define WINDOW_DEFAULT_WIDTH 1050
#define OPTION_NORMAL_WIDTH 150
#define OPTION_NORMAL_HEIGHT 20
#define OPTION_FRESH_WIDTH 80
#define OPTION_CLOSE_SIZE 15
#define WM_CREATE_NEW_PAGE WM_USER + 100 
#define WM_TITLE_CHANGE WM_USER + 101

